config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  devise_for :users
  root 'top#index'
  resources :users, only: [:edit, :update,:show]
  resources :maigos
  resources :maigos do
    resources :comments, only: :create
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :maigo  
  belongs_to :user 
end

app/models/maigo.rb
class Maigo < ApplicationRecord
  belongs_to :user
  validates :image,:name,:address, presence: true
  has_many :comments
  
mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :maigo
  has_many :comments

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new(comment_params)
    if comment.save
      redirect_to maigo_path(params[:maigo_id])
    else
      flash[:notice] = "コメントできませんでした"
    end

  end

  
  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, maigo_id: params[:maigo_id])
  end
end

app/controllers/maigos_controller.rb
class MaigosController < ApplicationController
  before_action :set_maigo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only:[:create,:edit,:update,:destroy]

  # GET /maigos
  # GET /maigos.json
  def index
    @maigos = Maigo.all.order(created_at: :desc)
    # @maigo = Maigo.edit(maigo_params)
  end

  # GET /maigos/1
  # GET /maigos/1.json
  def show
    @maigo = Maigo.find(params[:id])
    @items = Maigo.all
    @comment = Comment.new
    @comments = @maigo.comments.includes(:user)
  end

  # GET /maigos/new
  def new
    flash[:notice] = "※登録ユーザーのみ新規登録が可能です。ログインしてください。" unless user_signed_in?
    @maigo = Maigo.new
  end

  # GET /maigos/1/edit
  def edit
  end

  # POST /maigos
  # POST /maigos.json
  def create
    @maigo = Maigo.new(maigo_params)

    respond_to do |format|
      if @maigo.save
        format.html { redirect_to @maigo, notice: '迷子の登録が出来ました' }
        format.json { render :show, status: :created, location: @maigo }
      else
        format.html { render :new }
        format.json { render json: @maigo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maigos/1
  # PATCH/PUT /maigos/1.json
  def update
    respond_to do |format|
      if @maigo.update(maigo_params)
        format.html { redirect_to @maigo, notice:  '迷子情報を更新しました' }
        format.json { render :show, status: :ok, location: @maigo }
      else
        format.html { render :edit }
        format.json { render json: @maigo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maigos/1
  # DELETE /maigos/1.json
  def destroy
    @maigo.destroy
    respond_to do |format|
      format.html { redirect_to maigos_url, notice: '迷子情報の削除が完了しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maigo
      @maigo = Maigo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def maigo_params
      params.require(:maigo).permit(:image, :name, :age, :sex, :address, :content).merge(user_id: current_user.id)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title LostCatSearch
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/maigos/_main.maigo.html.haml
.maigo_top
  .header-mayoineko
    迷い猫
  .maigo-reg 
    .btn
      = link_to '猫を登録', new_maigo_path
      
  .content-maigo
    - @maigos.each do |maigo|
      = link_to maigo_path(maigo.id) do
        .maigo-data
          .maigo-data__image
            = image_tag maigo.image.url, class: 'maigo-data__image__image' if maigo.image.present?
          .maigo-data__name
            お名前：
            = maigo.name
          .maigo-data__age
            年齢：
            = maigo.age
            才
          .maigo-data__sex
            性別：
            = maigo.sex
          .maigo-data__address
            住所：
            = maigo.address
          .maigo-data__content
            失踪日、特徴など：

            = maigo.content
          .maigo-data__user-name
            飼い主さん：
            = maigo.user.name
    
  .page_top_btn
    = link_to "#" do
      .page_top__icon
        = icon('fas','angle-double-up',class: 'icon')
      .page_top__text
        TOP

app/views/maigos/edit.html.haml
.form_top
  .header-form
    迷子情報の変更
  = form_for @maigo do |f|

    .form-box
      .field__input
        = f.label :image do
          = f.label :画像
          = icon('fas', 'image', class: 'icon')
          = f.file_field :image, required: true,class: 'hidden'
          %span
            必須
      .field__input
        = f.label :名前
        = f.text_field :name,required: true,placeholder: '猫の名前', class: 'm-form'
        %span
          必須
      .field__input
        = f.label :年齢
        = f.number_field :age,placeholder: '半角数字（不明時は大体で可）', class: 'm-form'
        %span_2
          任意
      .field__input
        = f.label :性別
        = f.text_field :sex,placeholder: 'オス、メス、不明（去勢の有無）', class: 'm-form'
        %span_2
          任意
      .field__input
        = f.label :場所
        = f.text_field :address,required: true,placeholder: '○○市番地付近など失踪場所', class: 'm-form'
        %span
          必須
      .field__input
        = f.label :備考
        = f.text_area :content,required: true,placeholder: '失踪日、特徴', class: 'm-form2'
        %span
          必須
      .actions
        = f.submit '登録', class: 'm-submit'



  = link_to 'トップページに戻る', maigos_path

app/views/maigos/index.html.haml
.wrapper
  = render partial:"top/side_bar"
  = render "main.maigo"



-#         %td= link_to 'Show', maigo
-#         %td= link_to 'Edit', edit_maigo_path(maigo)
-#         %td= link_to 'Destroy', maigo, method: :delete, data: { confirm: 'Are you sure?' }

app/views/maigos/new.html.haml
.form_top
  .header-form
    迷子の登録フォーム
  = form_for @maigo do |f|
    - if @maigo.errors.any?
      #error_explanation
        %h2= "#{@maigo.errors.full_messages.count} 件のエラーが発生しました。"
        %ul
          - @maigo.errors.full_messages.each do |message|
            %li= message

      
    .form-box
      .field__input
        = f.label :image do
          = f.label :画像
          = icon('fas', 'image', class: 'icon')
          = f.file_field :image, required: true,class: 'hidden'
          %span
            必須
      .field__input
        = f.label :名前
        = f.text_field :name,required: true,placeholder: '猫の名前', class: 'm-form'
        %span
          必須
      .field__input
        = f.label :年齢
        = f.number_field :age,placeholder: '半角数字（不明時は大体で可）', class: 'm-form'
        %span_2
          任意
      .field__input
        = f.label :性別
        = f.text_field :sex,placeholder: 'オス、メス、不明（去勢の有無）', class: 'm-form'
        %span_2
          任意
      .field__input
        = f.label :場所
        = f.text_field :address,required: true,placeholder: '○○市番地付近など失踪場所', class: 'm-form'
        %span
          必須
      .field__input
        = f.label :備考
        = f.text_area :content,required: true,placeholder: '失踪日、特徴', class: 'm-form2'
        %span
          必須
        
        .actions
          = f.submit '登録', class: 'm-submit'
      .exit-box
        = link_to '戻る', maigos_path

app/views/maigos/show.html.haml
.wrapper
  = render partial:"top/side_bar"

  .maigo_top
    .header-mayoineko
      探しています
    .show-mayoineko
      .content-box
        .maigo-show
          .maigo-show__image
            = image_tag @maigo.image.url
          .maigo-show__name
            お名前：
            = @maigo.name
          .maigo-show__age
            年齢：
            = @maigo.age
            才
          .maigo-show__sex
            性別：
            = @maigo.sex
          .maigo-show__address
            住所：
            = @maigo.address
          .maigo-show__content
            失踪日、特徴など：
            = @maigo.content
          .maigo-show__user-name
            飼い主さん：
            = @maigo.user.name
        - if user_signed_in? && current_user.id == @maigo.user_id
          = link_to '編集する', edit_maigo_path(@maigo)
          = link_to '削除する', maigo_path(@maigo), method: :delete
          = link_to '戻る', maigos_path
        - else
          = link_to '戻る', maigos_path
          
        .commentContainer
          .commentContainer__comments
            %h4＜コメント一覧＞
            - if @comments.presence
              - @comments.each do |comment|
                .commentContainer__comments__name
                  = comment.user.name
                  = comment.created_at.strftime("%Y年%m月%d日 %H時%M分")
                  
                .commentContainer__comments__comment
                  = comment.text
                  
            - else
              = "コメントはありません"
      
            .commentContainer__form
              - if current_user
                = form_for [@maigo,@comment] do |f|
                  .field__input
                    = f.label :コメント投稿
                    = f.text_area :text,required: true,placeholder: '※発言の責任は投稿者が負うものとし、名誉棄損など内容により法的処置を行う場合があります。', class: 'comment-box'
                    .actions
                      = f.submit "コメントする", class: "comment-btn"
              - else
                = link_to "コメントの投稿には新規登録/ログインが必要です", new_user_session_path

app/views/top/_main_index.html.haml
.main_index
  .introduce 
    家族を探すためのアプリケーション
    .main-image
      = image_tag"oo.png"
  
  .contents-intro  
    .intro-title
      %p.comment
        『大事なあの子、探しています。』<br>
      %p.comment
        まずは掲示板でいなくなってしまった猫ちゃんの情報を登録しましょう。<br>

      %p.comment
        『早く見つけてあげたいから、張り紙も作らなきゃ』<br>
        そんな飼い主さんは簡単作成フォームを利用して、PDFを作成可能。<br>
        印刷してご近所さんに配布、勿論そのままSNSに貼ってもOKです<br>

      


  .card-section
    .card-list
      %ul.card-list-ny
        %li.card-list-ny__item
          .card-img
            = image_tag"sagasu.jpg"
          .card-text
            迷い猫を探す<br>
            いなくなった子を掲示板でお知らせ
        %li.card-list-ny__item
          .card-img
            = image_tag"pos.jpg"
          %p.card-text
            張り紙を作る<br>
            フォームに入力するだけですぐに張り紙が完成。
  .page_top_btn
    = link_to "#" do
      .page_top__icon
        = icon('fas','angle-double-up',class: 'icon')
      .page_top__text
        TOP
  .footer
    ©2020- Lost Cat Search / produced by koz

app/views/top/_side_bar.html.haml
.side_bar

  .side-header
    .side-header__logo
      .image
        = image_tag"logo.png"

  .side-content
    .side-content__list
      %ul.side-content__list
        %li.side-content__list__home
          = link_to "/" do
            ="HOME"
        .cp_hr02

        %li.side-content__list__lost-cat
          = link_to maigos_path do  
            ="迷い猫"
        .cp_hr02

        %li.side-content__list__poster-create
          = link_to "#" do  
            ="ポスターを作る"
        .cp_hr02

    .link-icons
      %ul.link-icons__icon
        %li.link-icons__icon__fb
          = link_to "https://www.facebook.com/" do
            =icon("fab",'facebook',class: 'icon')
        %li.link-icons__icon__tw
          = link_to "https://twitter.com" do 
            =icon("fab",' fa-twitter-square',class: 'icon')     
        %li.link-icons__icon__inst
          = link_to "https://www.instagram.com" do
            =icon("fab",'instagram',class: 'icon')

    .login-form
      %ul.login-form__box
        %li.login-form__box__user-name
        - if user_signed_in?
          = current_user.name 
          さん
          %li.side-header__box__sign-in
            = link_to edit_user_path(current_user) do
              =icon('fas', 'cog', class: 'icon')
        - else 
          ="ゲストさん"
          %li.side-header__box__sign-in
            = link_to  new_user_registration_path do
              =icon('fas', 'cog', class: 'icon')

app/views/top/index.html.haml
.wrapper
  = render "side_bar"
  = render "main_index"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト",destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'

app/views/users/show.html.haml
.wrapper
  = render "top/side_bar"
  .main_index